### ISSUE TITLE
Finish Multivariate for major release (1.0.0)

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/addons#6]
I've got a prototype module manager working that lists modules in the master branch, but only includes modules with version >= 1. Therefore, do you have time to "finish off" the Multivariate module (there are a few reference class warnings, plus you mentioned some others)? I don't expect to push the module manager for at least a few more weeks, so if you haven't been able to update it before then I'm happy to do so myself.

**Comment by daniel-barnett** [comment]
I should have the time - it shouldn't be anything too major

**Comment by tmelliott** [comment]
@daniel-barnett I quickly fixed the above issue to prevent warnings on startup - have you made any further progress, or can I bump to 1.0.0 so it shows up within iNZight's module manager?

**Comment by daniel-barnett** [comment]
I haven't made any progress yet, so yep, I'm happy to have the version bumped :)
